name: default
kind: pipeline

steps:
  - name: build
    image: node:alpine
    commands:
      - yarn install
      - yarn build
  - name: deploy
    image: jimfx/sftp
    environment:
      FTP_USERNAME:
        from_secret: FTP_USERNAME
      FTP_PASSWORD:
        from_secret: FTP_PASSWORD
      PLUGIN_HOSTNAME: jim-fx.com:2221
      PLUGIN_DEST_DIR: /share/mesh
      PLUGIN_SRC_DIR: /drone/src/build
